import {
  NavAnnouncementIcon,
  NavApplicationIcon,
  NavDashboardIcon,
  NavExamTemplateIcon,
  NavLicenseCodeIcon,
  NavPlanCatalogIcon,
  NavQuestionBankIcon,
  NavSettingsIcon,
  NavSupportTicketIcon,
  NavTaskTypeIcon,
  NavTenantIcon,
  UsersIcon,
} from "@pte/ui";
import type { NavItem } from "@/features/auth/components";
import {
  ACADEMIC_ROLES,
  PLATFORM_ADMIN_ONLY,
  PLATFORM_OPERATIONS_ROLES,
} from "@/features/auth/constants";
import { ADMIN_NAV_TEXT as T } from "./navigationConstants";

export const ADMIN_NAV: NavItem[] = [
  { label: T.OVERVIEW, labelKey: "nav.overview", href: "/admin", icon: <NavDashboardIcon />, section: T.HOME_SECTION, sectionKey: "nav.home" },
  { label: T.TENANTS, labelKey: "nav.tenants", href: "/admin/tenants", icon: <NavTenantIcon />, section: T.TENANTS_SECTION, sectionKey: "nav.tenants", requiredRoles: PLATFORM_OPERATIONS_ROLES },
  {
    label: T.APPLICATIONS,
    labelKey: "nav.applications",
    href: "/admin/applications",
    icon: <NavApplicationIcon />,
    section: T.TENANTS_SECTION,
    sectionKey: "nav.tenants",
    requiredRoles: PLATFORM_OPERATIONS_ROLES,
  },
  {
    label: T.PLATFORM_USERS,
    labelKey: "nav.platformUsers",
    href: "/admin/platform-users",
    icon: <UsersIcon />,
    section: T.TENANTS_SECTION,
    sectionKey: "nav.tenants",
    requiredRoles: PLATFORM_ADMIN_ONLY,
  },
  {
    label: T.PLAN_CATALOG,
    labelKey: "nav.planCatalog",
    href: "/admin/plans",
    icon: <NavPlanCatalogIcon />,
    section: T.COMMERCIAL_SECTION,
    sectionKey: "nav.commercial",
    requiredRoles: PLATFORM_OPERATIONS_ROLES,
  },
  {
    label: T.LICENSE_CODES,
    labelKey: "nav.licenseCodes",
    href: "/admin/license-codes",
    icon: <NavLicenseCodeIcon />,
    section: T.COMMERCIAL_SECTION,
    sectionKey: "nav.commercial",
    requiredRoles: PLATFORM_OPERATIONS_ROLES,
  },
  {
    label: T.PLATFORM_SETTINGS,
    labelKey: "nav.platformSettings",
    href: "/admin/settings",
    icon: <NavSettingsIcon />,
    section: T.COMMERCIAL_SECTION,
    sectionKey: "nav.commercial",
    requiredRoles: PLATFORM_ADMIN_ONLY,
  },
  {
    label: T.ANNOUNCEMENTS,
    labelKey: "nav.announcements",
    href: "/admin/announcements",
    icon: <NavAnnouncementIcon />,
    section: T.COMMERCIAL_SECTION,
    sectionKey: "nav.commercial",
    requiredRoles: PLATFORM_OPERATIONS_ROLES,
  },
  {
    label: T.QUESTION_BANK,
    labelKey: "nav.questionBank",
    href: "/admin/questions",
    icon: <NavQuestionBankIcon />,
    section: T.CONTENT_SECTION,
    sectionKey: "nav.content",
    requiredRoles: ACADEMIC_ROLES,
  },
  {
    label: T.TASK_TYPES,
    labelKey: "nav.taskTypes",
    href: "/admin/question-types",
    icon: <NavTaskTypeIcon />,
    section: T.CONTENT_SECTION,
    sectionKey: "nav.content",
    requiredRoles: ACADEMIC_ROLES,
  },
  {
    label: T.EXAM_TEMPLATES,
    labelKey: "nav.examTemplates",
    href: "/admin/exam-template",
    icon: <NavExamTemplateIcon />,
    section: T.CONTENT_SECTION,
    sectionKey: "nav.content",
    requiredRoles: ACADEMIC_ROLES,
  },
  {
    label: T.SUPPORT_TICKETS,
    labelKey: "nav.supportTickets",
    href: "/admin/support-tickets",
    icon: <NavSupportTicketIcon />,
    section: T.SUPPORT_SECTION,
    sectionKey: "nav.support",
    requiredRoles: PLATFORM_OPERATIONS_ROLES,
  },
];

export const HOST_NAV: NavItem[] = [
  { label: T.OVERVIEW, labelKey: "nav.overview", href: "/host", icon: <NavDashboardIcon />, section: T.HOME_SECTION, sectionKey: "nav.home" },
];
