export const ADMIN_NAV_TEXT = {
  OVERVIEW: "Overview",
  TENANTS: "Tenants",
  APPLICATIONS: "Applications",
  PLAN_CATALOG: "Plan catalog",
  LICENSE_CODES: "License codes",
  PLATFORM_SETTINGS: "Platform settings",
  QUESTION_BANK: "Question Bank",
  TASK_TYPES: "Task Type Catalog",
  EXAM_TEMPLATES: "Exam Templates",
  HOME_SECTION: "Home",
  TENANTS_SECTION: "Tenants",
  COMMERCIAL_SECTION: "Commercial",
  CONTENT_SECTION: "Content",
} as const;
