export const APPLICATIONS_QUERY_KEY = ["commercialization", "applications"] as const;
export const APPLICATION_QUERY_KEY = (publicId: string) =>
  ["commercialization", "application", publicId] as const;
export const PLANS_QUERY_KEY = ["commercialization", "plans"] as const;
export const SETTINGS_QUERY_KEY = ["commercialization", "settings"] as const;
export const LICENSE_CODES_QUERY_KEY = ["commercialization", "license-codes"] as const;

export const PLATFORM_SETTINGS_TEXT = {
  TITLE: "Platform settings",
  SUBTITLE: "Set defaults used by tenant subscriptions and quota checks.",
  PANEL_TITLE: "Commercial defaults",
  PANEL_SUBTITLE: "These values are controlled by platform administrators.",
  LOADING: "Loading settings...",
  SAVE: "Save",
  ERROR: "Settings could not be loaded or saved.",
  SAVED: (key: string) => `Setting ${key} saved.`,
} as const;

export const ADMIN_APPLICATIONS_TEXT = {
  TITLE: "Tenant applications",
  SUBTITLE: "Review organization requests before workspace access is created.",
  FILTER_ARIA_LABEL: "Filter applications by status",
  ALL_STATUSES: "All statuses",
  PENDING: "Pending",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  COLUMN_ORGANIZATION: "Organization",
  COLUMN_CONTACT: "Contact",
  COLUMN_TYPE: "Type",
  COLUMN_TAX_CODE: "Tax code",
  COLUMN_STATUS: "Status",
  LOAD_ERROR: "Applications could not be loaded. Try again shortly.",
  RETRY: "Retry",
  OVERVIEW_TITLE: "Application overview",
  OVERVIEW_SUBTITLE: "Tenant application status at a glance.",
  TOTAL: "Total applications",
  NEEDS_REVIEW: "Needs review",
  APPROVED_COUNT: "Approved",
  VIEW_DETAILS: "View details",
  LOADING: "Loading applications...",
  EMPTY: "No applications found",
  FILTER_EMPTY: "Try another status filter.",
  EMPTY_VALUE: "—",
} as const;

export const ADMIN_APPLICATION_DETAIL_TEXT = {
  LOADING: "Loading application...",
  BACK: "← Back to applications",
  NOT_FOUND: "This application was not found or is no longer available.",
  UPDATE_ERROR: "The application could not be updated. Please try again.",
  APPROVED: "Application approved. Verify the Host account manually; credentials delivery is not confirmed here.",
  LOAD_ERROR: "Application details could not be loaded.",
  FORBIDDEN: "You do not have permission to view this application.",
  RETRY: "Retry",
  UNCERTAIN: "The result is uncertain. Refresh the application before trying the action again.",
  REFRESH_ERROR: "The action result is uncertain and the latest application state could not be loaded. Do not retry yet.",
  REQUESTED_CODE: (code: string) => `Requested code ${code}`,
  DETAILS_TITLE: "Application details",
  DETAILS_SUBTITLE: "Submitted organization information.",
  REVIEW_TITLE: "Review decision",
  REVIEW_SUBTITLE: "Approve access or record a reason for rejection.",
  CURRENT_STATUS: "Current status",
  REJECTION_REASON_LABEL: "Rejection reason",
  REJECTION_REASON_PLACEHOLDER: "Explain what must be corrected",
  APPROVING: "Approving...",
  APPROVE: "Approve application",
  REJECTING: "Rejecting...",
  REJECT: "Reject application",
  ORGANIZATION_TYPE: "Organization type",
  REQUESTED_TENANT_CODE: "Requested tenant code",
  WORK_EMAIL: "Work email",
  PHONE: "Phone number",
  TAX_CODE: "Tax code",
  REVIEWED_BY: "Reviewed by",
  REVIEWED_AT: "Reviewed at",
  EMPTY_VALUE: "—",
} as const;

export const PLAN_CATALOG_TEXT = {
  TITLE: "Plan catalog",
  SUBTITLE: "Configure packages available to approved tenants.",
  ADD: "+ Add plan",
  OVERVIEW_TITLE: "Plan overview",
  OVERVIEW_SUBTITLE: "Catalog status at a glance.",
  TOTAL: "Total plans",
  ACTIVE: "Active plans",
  DRAFT: "Draft plans",
  EDIT_TITLE: "Edit plan",
  CREATE_TITLE: "Create plan",
  FORM_SUBTITLE: "Only ACTIVE plans are visible to tenants.",
  SECTION_GENERAL: "General",
  SECTION_PRICING: "Pricing & limits",
  PLAN_NAME: "Plan name",
  PLAN_TYPE: "Plan type",
  EXAM_PACKAGE: "Exam package",
  STUDENT_CAPACITY: "Student capacity",
  DESCRIPTION: "Description",
  PRICE: "Price",
  CURRENCY: "Currency",
  DURATION: "Duration (days)",
  STUDENTS_PER_SESSION: "Students per session",
  EXTRA_STUDENT_SLOTS: "Extra student slots",
  MAX_STUDENT_COUNT_HELPER: "Maximum 2,000 students.",
  CURRENCY_HELPER: "Catalog plans use VND. Legacy values are not converted automatically.",
  NAME_MAX_ERROR: "Plan name must be at most 255 characters.",
  DESCRIPTION_MAX_ERROR: "Description must be at most 255 characters.",
  PRICE_ERROR: "Enter a non-negative price with at most 17 integer digits and 2 decimals.",
  INTEGER_ERROR: (max: number) => `Enter a whole number from 1 to ${max}.`,
  STALE_VERSION_TITLE: "This plan changed while you were editing",
  STALE_VERSION_DESCRIPTION: "Your form still contains the values you entered. Review the latest server values before deciding what to do.",
  SERVER_VALUES: "Latest server values",
  RELOAD_SERVER: "Reload server values",
  KEEP_MY_CHANGES: "Keep my changes",
  VERSION_LABEL: "Version",
  VERSION: (version: number) => `Version ${version}`,
  SAVE_CHANGES: "Save changes",
  CREATE_DRAFT: "Create draft",
  CANCEL: "Cancel",
  CATALOG_TITLE: "Published catalog",
  CATALOG_SUBTITLE: "Separate exam access from permanent student capacity.",
  FILTER_ARIA_LABEL: "Filter plans by type",
  ALL: "All",
  CAPACITY_ADD_ONS: "Capacity add-ons",
  TABLE_PLAN: "Plan",
  TABLE_PRICE: "Price",
  TABLE_TERM: "Term",
  TABLE_CAPACITY: "Capacity",
  TABLE_STATUS: "Status",
  DAYS: (count: number) => `${count} days`,
  PERMANENT: "Permanent",
  SESSION_CAPACITY: (count: number | string) => `${count} / session`,
  EXTRA_STUDENTS: (count: number | string) => `+${count} students`,
  EDIT: "Edit",
  ACTIVATE: "Activate",
  ARCHIVE: "Archive",
  DELETE_DRAFT: "Delete draft",
  DELETE_CONFIRM_TITLE: "Delete this draft?",
  DELETE_CONFIRM_DESCRIPTION: "This draft will be removed from the catalog. Audit history is retained, but it cannot be restored from this UI.",
  DELETED_SUCCESS: "Plan draft deleted.",
  DELETE_BLOCKED: "This draft has usage history and cannot be deleted.",
  ARCHIVE_BLOCKED: "Archive is blocked while issued codes remain redeemable. Revoke them or wait for expiry.",
  CAPABILITIES_UNAVAILABLE: "Reload to check which cleanup actions are available.",
  ARCHIVE_CONFIRM_TITLE: "Archive this plan?",
  ARCHIVE_CONFIRM_DESCRIPTION:
    "This plan will no longer be available for new purchases. Existing subscriptions and audit history are retained. Retirement cannot be undone from this UI.",
  ARCHIVE_CONFIRM_BUTTON: "Archive plan",
  LOADING: "Loading plans...",
  EMPTY: "No plans found",
  ERROR: "Plans could not be loaded or saved.",
  UPDATED: "Plan updated.",
  CREATED: "Plan draft created.",
  ACTIVATED: "Plan activated.",
  ARCHIVED_SUCCESS: "Plan archived.",
  EMPTY_VALUE: "—",
} as const;

export const LICENSE_CODES_TEXT = {
  TITLE: "License codes",
  SUBTITLE: "Issue and track redeemable exam package codes.",
  ISSUE_TITLE: "Issue a code",
  ISSUE_SUBTITLE: "Codes are limited to an active exam package.",
  PLAN_LABEL: "Plan",
  PLAN_PLACEHOLDER: "Select active exam package",
  REFRESH_PLANS: "Refresh plans",
  EXPIRY_LABEL: "Code expiry",
  EXPIRY_HELP: (zone: string, utc: string) => `Time zone: ${zone}. UTC: ${utc}. Leave empty for no code expiry.`,
  RETRY_ISSUE: "Recover issuance result",
  NEW_ISSUE: "Start a new issuance",
  NEW_ISSUE_CONFIRM: "Start another issuance?",
  NEW_ISSUE_WARNING: "The previous request may already have created a license. Recover its result first. Starting another request can create a second license.",
  UNCERTAIN: "The issuance result has not been confirmed. Recover this request before starting another issuance.",
  ISSUE_REJECTED: "This request was rejected. Start a new issuance to correct the input.",
  ISSUE_PENDING: "Confirming the issuance result…",
  REJECTED_NEW_ISSUE: "Clear this rejected request so you can correct the plan or expiry.",
  INVALID_EXPIRY: "Enter a valid future date and time.",
  ISSUE: "Issue code",
  ISSUED_TITLE: "Issued codes",
  ISSUED_SUBTITLE: "Codes and status are loaded from the billing API.",
  CODE: "Code",
  PLAN_ID: "Plan ID",
  ISSUED: "Issued",
  EXPIRES: "Expires",
  STATUS: "Status",
  REVOKE: "Revoke",
  LOADING: "Loading codes...",
  EMPTY: "No license codes found",
  REVOKE_TITLE: "Revoke license code?",
  REVOKE_DESCRIPTION: "Review the live subscription impact before confirming. The action cannot be undone.",
  REVOKE_CONFIRM: "Revoke code",
  REVOKE_PREVIEW_LOADING: "Loading the current impact...",
  REVOKE_PREVIEW_ERROR: "The revoke preview could not be loaded. Refresh and try again.",
  REVOKE_PREVIEW_EXPIRED: "This preview expired. A fresh preview is required.",
  REVOKE_IMPACT_CODE_ONLY: "Code only",
  REVOKE_IMPACT_EXAM: "Exam subscription",
  REVOKE_SUBSCRIPTION: "Subscription",
  REVOKE_SCHEDULED: "Scheduled sessions cancelled",
  REVOKE_OPEN: "Open sessions preserved",
  REVOKE_CLOSED: "Closed sessions preserved",
  REVOKE_REASON_HELP: "Give a short audit reason. This reason is retained with the code.",
  REVOKE_ACK_SUBSCRIPTION: "I understand the linked exam subscription will be cancelled.",
  REVOKE_ACK_SCHEDULED: "I understand all currently scheduled sessions in this scope will be cancelled.",
  REVOKE_ACK_OPEN_CLOSED: "I understand open and closed sessions will be preserved.",
  REVOKE_SCOPE_CHANGED: "The scope changed while you were confirming. Review the refreshed preview and acknowledge it again.",
  REVOKE_PREVIEW_RETRY: "Refresh preview",
  REVOKE_NO_SCHEDULED: "No scheduled sessions",
  REVOKE_EXPIRED_CODE: "Expired codes cannot be revoked.",
  ISSUED_SUCCESS: (id: string) => `License issuance ${id} confirmed.`,
  RECOVERED_SUCCESS: (id: string) => `Previous license issuance ${id} recovered.`,
  REVOKED_SUCCESS: (code: string) => `License code ${code} revoked.`,
  ERROR: "License codes could not be loaded or saved.",
  REVOKE_REASON: "Revoked by platform administrator",
  EMPTY_VALUE: "—",
} as const;
