export const APPLICATIONS_QUERY_KEY = ["commercialization", "applications"] as const;
export const PLANS_QUERY_KEY = ["commercialization", "plans"] as const;
export const SETTINGS_QUERY_KEY = ["commercialization", "settings"] as const;
export const LICENSE_CODES_QUERY_KEY = ["commercialization", "license-codes"] as const;

export const PLATFORM_SETTINGS_TEXT = {
  TITLE: "Platform settings",
  SUBTITLE: "Set defaults used by tenant subscriptions and quota checks.",
  PANEL_TITLE: "Commercial defaults",
  PANEL_SUBTITLE: "These values are controlled by platform administrators.",
  LOADING: "Loading settings...",
  SAVE: "Save",
  ERROR: "Settings could not be loaded or saved.",
  SAVED: (key: string) => `Setting ${key} saved.`,
} as const;

export const ADMIN_APPLICATIONS_TEXT = {
  TITLE: "Tenant applications",
  SUBTITLE: "Review organization requests before workspace access is created.",
  FILTER_ARIA_LABEL: "Filter applications by status",
  ALL_STATUSES: "All statuses",
  PENDING: "Pending",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  COLUMN_ORGANIZATION: "Organization",
  COLUMN_CONTACT: "Contact",
  COLUMN_TYPE: "Type",
  COLUMN_TAX_CODE: "Tax code",
  COLUMN_STATUS: "Status",
  LOAD_ERROR: "Applications could not be loaded. Try again shortly.",
  OVERVIEW_TITLE: "Application overview",
  OVERVIEW_SUBTITLE: "Tenant application status at a glance.",
  TOTAL: "Total applications",
  NEEDS_REVIEW: "Needs review",
  APPROVED_COUNT: "Approved",
  VIEW_DETAILS: "View details",
  LOADING: "Loading applications...",
  EMPTY: "No applications found",
  FILTER_EMPTY: "Try another status filter.",
  EMPTY_VALUE: "—",
} as const;

export const ADMIN_APPLICATION_DETAIL_TEXT = {
  LOADING: "Loading application...",
  BACK: "← Back to applications",
  NOT_FOUND: "This application was not found or is no longer available.",
  UPDATE_ERROR: "The application could not be updated. Please try again.",
  APPROVED: "Application approved. One-time host credentials were sent to the contact email.",
  REQUESTED_CODE: (code: string) => `Requested code ${code}`,
  DETAILS_TITLE: "Application details",
  DETAILS_SUBTITLE: "Submitted organization information.",
  REVIEW_TITLE: "Review decision",
  REVIEW_SUBTITLE: "Approve access or record a reason for rejection.",
  CURRENT_STATUS: "Current status",
  REJECTION_REASON_LABEL: "Rejection reason",
  REJECTION_REASON_PLACEHOLDER: "Explain what must be corrected",
  APPROVING: "Approving...",
  APPROVE: "Approve application",
  REJECTING: "Rejecting...",
  REJECT: "Reject application",
  ORGANIZATION_TYPE: "Organization type",
  REQUESTED_TENANT_CODE: "Requested tenant code",
  WORK_EMAIL: "Work email",
  PHONE: "Phone number",
  TAX_CODE: "Tax code",
  EMPTY_VALUE: "—",
} as const;

export const PLAN_CATALOG_TEXT = {
  TITLE: "Plan catalog",
  SUBTITLE: "Configure packages available to approved tenants.",
  ADD: "+ Add plan",
  OVERVIEW_TITLE: "Plan overview",
  OVERVIEW_SUBTITLE: "Catalog status at a glance.",
  TOTAL: "Total plans",
  ACTIVE: "Active plans",
  DRAFT: "Draft plans",
  EDIT_TITLE: "Edit plan",
  CREATE_TITLE: "Create plan",
  FORM_SUBTITLE: "Only ACTIVE plans are visible to tenants.",
  PLAN_NAME: "Plan name",
  PLAN_TYPE: "Plan type",
  EXAM_PACKAGE: "Exam package",
  STUDENT_CAPACITY: "Student capacity",
  DESCRIPTION: "Description",
  PRICE: "Price",
  CURRENCY: "Currency",
  DURATION: "Duration (days)",
  STUDENTS_PER_SESSION: "Students per session",
  EXTRA_STUDENT_SLOTS: "Extra student slots",
  SAVE_CHANGES: "Save changes",
  CREATE_DRAFT: "Create draft",
  CANCEL: "Cancel",
  CATALOG_TITLE: "Published catalog",
  CATALOG_SUBTITLE: "Separate exam access from permanent student capacity.",
  FILTER_ARIA_LABEL: "Filter plans by type",
  ALL: "All",
  CAPACITY_ADD_ONS: "Capacity add-ons",
  TABLE_PLAN: "Plan",
  TABLE_PRICE: "Price",
  TABLE_TERM: "Term",
  TABLE_CAPACITY: "Capacity",
  TABLE_STATUS: "Status",
  DAYS: (count: number) => `${count} days`,
  PERMANENT: "Permanent",
  SESSION_CAPACITY: (count: number | string) => `${count} / session`,
  EXTRA_STUDENTS: (count: number | string) => `+${count} students`,
  EDIT: "Edit",
  ACTIVATE: "Activate",
  ARCHIVE: "Archive",
  LOADING: "Loading plans...",
  EMPTY: "No plans found",
  ERROR: "Plans could not be loaded or saved.",
  UPDATED: "Plan updated.",
  CREATED: "Plan draft created.",
  EMPTY_VALUE: "—",
} as const;

export const LICENSE_CODES_TEXT = {
  TITLE: "License codes",
  SUBTITLE: "Issue and track redeemable exam package codes.",
  ISSUE_TITLE: "Issue a code",
  ISSUE_SUBTITLE: "Codes are limited to an active exam package.",
  PLAN_LABEL: "Plan",
  PLAN_PLACEHOLDER: "Select active exam package",
  EXPIRY_LABEL: "Code expiry",
  ISSUE: "Issue code",
  ISSUED_TITLE: "Issued codes",
  ISSUED_SUBTITLE: "Codes and status are loaded from the billing API.",
  CODE: "Code",
  PLAN_ID: "Plan ID",
  ISSUED: "Issued",
  EXPIRES: "Expires",
  STATUS: "Status",
  REVOKE: "Revoke",
  LOADING: "Loading codes...",
  EMPTY: "No license codes found",
  REVOKE_TITLE: "Revoke license code?",
  REVOKE_DESCRIPTION: "This code will no longer be redeemable. The action cannot be undone.",
  REVOKE_CONFIRM: "Revoke code",
  ISSUED_SUCCESS: (code: string) => `License code ${code} issued.`,
  REVOKED_SUCCESS: (code: string) => `License code ${code} revoked.`,
  ERROR: "License codes could not be loaded or saved.",
  REVOKE_REASON: "Revoked by platform administrator",
  EMPTY_VALUE: "—",
} as const;
