import type { CommercialPlan, LicenseCode, TenantApplication } from "./types";

export const DEMO_APPLICATIONS: TenantApplication[] = [
  {
    id: "app-104821",
    reference: "APP-2026-104821",
    organizationName: "Bright English Center",
    organizationType: "Language center",
    representative: "Linh Nguyen",
    email: "linh@brightenglish.edu",
    phone: "+84 901 222 456",
    tenantCode: "BRIGHT",
    submittedAt: "Sep 16, 2026 · 09:24",
    status: "PENDING",
  },
  {
    id: "app-104817",
    reference: "APP-2026-104817",
    organizationName: "North Star University",
    organizationType: "University",
    representative: "Minh Tran",
    email: "minh.tran@northstar.edu",
    phone: "+84 908 110 218",
    tenantCode: "NORTHSTAR",
    submittedAt: "Sep 15, 2026 · 15:40",
    status: "APPROVED",
  },
  {
    id: "app-104799",
    reference: "APP-2026-104799",
    organizationName: "Oakfield School",
    organizationType: "School",
    representative: "Ha Pham",
    email: "ha.pham@oakfield.edu",
    phone: "+84 903 882 114",
    tenantCode: "OAKFIELD",
    submittedAt: "Sep 14, 2026 · 11:08",
    status: "REJECTED",
    note: "Please provide a valid organization domain email.",
  },
];

export const DEMO_PLANS: CommercialPlan[] = [
  {
    id: "exam-starter",
    name: "Exam Starter",
    family: "EXAM_PACKAGE",
    status: "ACTIVE",
    price: "$49",
    duration: "30 days",
    capacity: "500 students / exam",
    description: "A focused package for one exam cycle.",
  },
  {
    id: "exam-growth",
    name: "Exam Growth",
    family: "EXAM_PACKAGE",
    status: "ACTIVE",
    price: "$129",
    duration: "90 days",
    capacity: "2,000 students / exam",
    description: "More room for multiple exam sessions.",
  },
  {
    id: "capacity-500",
    name: "Capacity +500",
    family: "STUDENT_CAPACITY",
    status: "ACTIVE",
    price: "$39",
    duration: "Permanent add-on",
    capacity: "+500 students",
    description: "Extend the tenant-wide student limit.",
  },
  {
    id: "capacity-1000",
    name: "Capacity +1,000",
    family: "STUDENT_CAPACITY",
    status: "DRAFT",
    price: "$69",
    duration: "Permanent add-on",
    capacity: "+1,000 students",
    description: "A larger permanent capacity extension.",
  },
];

export const DEMO_LICENSE_CODES: LicenseCode[] = [
  {
    id: "lic-001",
    code: "PTE-START-7K2M-9Q4R",
    plan: "Exam Starter",
    tenant: "Bright English Center",
    status: "ISSUED",
    issuedAt: "Sep 16, 2026",
    expiresAt: "Oct 16, 2026",
  },
  {
    id: "lic-002",
    code: "PTE-GROW-2N8P-4X1A",
    plan: "Exam Growth",
    tenant: "North Star University",
    status: "REDEEMED",
    issuedAt: "Sep 15, 2026",
    expiresAt: "Dec 14, 2026",
  },
];
