export const TENANT_PLANS_QUERY_KEY = ["commercialization", "tenant-plans"] as const;
export const ORDERS_QUERY_KEY = ["commercialization", "orders"] as const;
export const SUBSCRIPTIONS_QUERY_KEY = ["commercialization", "subscriptions"] as const;
export const STUDENT_QUOTA_QUERY_KEY = ["commercialization", "student-quota"] as const;

export const REDEEM_ERROR_MESSAGES: Record<string, string> = {
  LICENSE_CODE_NOT_FOUND: "License code was not found. Check the code and try again.",
  LICENSE_CODE_ALREADY_REDEEMED: "This license code has already been redeemed.",
  LICENSE_CODE_REVOKED: "This license code was revoked. Contact the issuer.",
  LICENSE_CODE_EXPIRED: "This license code has expired.",
  LICENSE_CODE_NOT_REDEEMABLE: "This license code cannot be redeemed.",
};

export const BILLING_TEXT = {
  BACK_TO_PLANS: "← Back to plans",
  CHECKOUT_TITLE: "Checkout",
  CHECKOUT_SUBTITLE: "Review your order before opening the secure payment page.",
  ORDER_ERROR: "The order could not be created.",
  SELECT_ACTIVE_PLAN: "Select an active plan from the catalog before checking out.",
  PENDING_PAYMENT_TITLE: "A payment for this plan is already pending",
  PENDING_PAYMENT_TEXT: "Finish the existing payment instead of creating a duplicate order.",
  CONTINUE_PAYMENT: "Continue payment",
  ORDER_SUMMARY: "Order summary",
  SELECTED_PACKAGE: "Selected package",
  TOTAL: "Total",
  SECURE_PAYMENT: "Secure payment",
  POWERED_BY_PAYOS: "Powered by PayOS",
  PAYOS_CHECKOUT: "PayOS checkout",
  WEBHOOK_CONFIRMATION: "Payment status is confirmed by the webhook.",
  CREATING_ORDER: "Creating order...",
  CONTINUE_TO_PAYOS: "Continue to PayOS",
  VIEW_PAYMENT_STATUS: "View payment status",
  PERMANENT_ADD_ON: "Permanent add-on",
  UP_TO_STUDENTS: (count: number | string) => `Up to ${count} students / session`,
  EXTRA_STUDENTS: (count: number | string) => `+${count} students`,
  EMPTY_VALUE: "—",
  ACTIVE_ACCESS_TITLE: "Active access",
  ACTIVE_ACCESS_SUBTITLE: "Your exam packages and permanent capacity add-ons.",
  MANAGE_PLANS: "Manage plans",
  SUBSCRIPTIONS_LOAD_ERROR: "Subscriptions could not be loaded.",
  EXPIRING_SOON:
    "One or more exam packages expire within 7 days. Review the catalog before scheduling another exam.",
  EXAM_SUBSCRIPTIONS: "Exam subscriptions",
  EXAM_SUBSCRIPTIONS_SUBTITLE: "Exam packages are independent subscriptions.",
  LOADING_SUBSCRIPTIONS: "Loading subscriptions...",
  NO_EXAM_SUBSCRIPTIONS: "No exam subscriptions found.",
  BROWSE_PLANS: "Browse plans",
  BROWSE_PLANS_SENTENCE: "Browse plans.",
  PLAN: (planId: string) => `Plan ${planId}`,
  STARTED: (date: string) => `Started ${date}`,
  EXPIRES: (date: string) => `Expires ${date}`,
  ACTIVATED: (date: string) => `Activated ${date}`,
  STUDENT_CAP: "Student cap",
  ACTIVATION: "Activation",
  LICENSE_KEY: "License key",
  MASKED_VALUE: "••••",
  SUBSCRIPTION_PERIOD: (started: string, expires: string) => `Started ${started} · Expires ${expires}`,
  CAPACITY_LEDGER: "Capacity ledger",
  CAPACITY_LEDGER_SUBTITLE: "Permanent quota purchased for this tenant.",
  NO_CAPACITY_ADD_ONS: "No capacity add-ons found.",
  REDEEM_TITLE: "Redeem license code",
  REDEEM_SUBTITLE: "Activate an exam package provided by the platform team.",
  REDEEM_SUCCESS_TITLE: "License redeemed",
  STUDENT_SLOTS_ADDED: (count: number) =>
    `Added ${count} student slots. Check Student capacity for the new limit.`,
  EXAM_PACKAGE_ACTIVATED: (expiresAt?: string) =>
    `Exam package activated${expiresAt ? ` until ${expiresAt}` : ""}. Check Active access for the subscription.`,
  LICENSE_CODE_PANEL: "License code",
  LICENSE_CODE_SUBTITLE: "Enter the code exactly as provided.",
  LICENSE_CODE_LABEL: "License code",
  LICENSE_CODE_PLACEHOLDER: "PTE-START-7K2M-9Q4R",
  REDEEMING: "Redeeming...",
  REDEEM: "Redeem code",
  VIEW_ACTIVE_ACCESS: "View active access",
  TOO_MANY_REDEMPTIONS: "Too many redemption attempts. Try again in a few minutes.",
  REDEEM_ERROR: "The license code could not be redeemed.",
  QUOTA_ERROR: "Quota could not be loaded or previewed.",
  QUOTA_TITLE: "Student capacity",
  QUOTA_SUBTITLE: "Check capacity before importing a roster.",
  ADD_CAPACITY: "Add capacity",
  LOADING_QUOTA: "Loading quota...",
  CAPACITY_OVERVIEW: "Capacity overview",
  CAPACITY_OVERVIEW_SUBTITLE: "Current student capacity and import preview.",
  STUDENTS_IN_TENANT: "Students in tenant",
  CURRENT_ROSTER_USAGE: (limit: number | string) => `of ${limit} total capacity`,
  REMAINING_CAPACITY: "Remaining capacity",
  STUDENTS_AVAILABLE: "students available",
  LAST_PREVIEW: "Last preview",
  STUDENTS_TO_ADD: "students to add",
  CURRENT_CAPACITY: "Current capacity",
  CURRENT_CAPACITY_SUBTITLE: "Free limit plus permanent capacity add-ons.",
  CURRENT_USAGE: (current: number | string, limit: number | string) => `${current} of ${limit} students`,
  STUDENT_CAPACITY_USED: "Student capacity used",
  USED: (percentage: number) => `${percentage}% used`,
  CAPACITY_ALMOST_FULL: "Capacity is almost full.",
  ADD_STUDENT_CAPACITY: "Add student capacity",
  CAPACITY_WARNING_SUFFIX: "before importing a large roster.",
  ROSTER_IMPORT_NOTICE: "Roster imports are checked before new students are added.",
  IMPORT_PREVIEW: "Import preview",
  IMPORT_PREVIEW_SUBTITLE: "Ask the backend whether a roster can be added before uploading it.",
  PREVIEW_QUOTA: "Preview quota",
  CURRENT: "Current",
  ADDING: "Adding",
  REMAINING: "Remaining",
  RESULT: "Result",
  ALLOWED: "Allowed",
  BLOCKED: "Blocked",
  PAYMENT_STATUS_TITLE: "Payment status",
  PAYMENT_STATUS_SUBTITLE: "Payment updates come from the payment webhook.",
  PAYMENT_STATUS_ERROR: "Payment status could not be loaded.",
  LOADING_PAYMENT_STATUS: "Loading payment status...",
  NO_ORDER: "No order is available yet. Start checkout from the plan catalog.",
  ORDER: (code: string | number) => `Order ${code}`,
  ORDER_PLAN_SUBTITLE: (planId: string, amount: string, currency: string) =>
    `Plan ${planId} · ${amount} ${currency}`,
  CREATED: (date: string) => `Created ${date}`,
  PAYMENT_PROCESSING: "Payment state is being processed.",
  PENDING_STATUS_NOTICE: "This page refreshes payment status while the order is pending.",
  PAYMENT_CONFIRMED: "Payment confirmed. Check Active access for the subscription.",
  TRY_CHECKOUT_AGAIN: "Try checkout again",
  ORDERS_TITLE: "Order history",
  ORDERS_SUBTITLE: "Review payments and purchased packages.",
  BROWSE_PLANS_ACTION: "Browse plans",
  ORDERS_LOAD_ERROR: "Orders could not be loaded. Try again shortly.",
  ORDERS_PANEL_TITLE: "Orders",
  ORDERS_PANEL_SUBTITLE: "Payment status is updated from PayOS webhook events.",
  ORDER_COLUMN: "Order",
  PLAN_ID_COLUMN: "Plan ID",
  AMOUNT_COLUMN: "Amount",
  DATE_COLUMN: "Date",
  STATUS_COLUMN: "Status",
  VIEW_DETAILS: "View details",
  LOADING_ORDERS: "Loading orders...",
  NO_ORDERS: "No orders found",
  TOTAL_ORDERS: (count: number) => `Showing ${count} order(s)`,
  PLANS_TITLE: "Plans & billing",
  PLANS_SUBTITLE: "Choose exam access or extend your student capacity.",
  PLANS_LOAD_ERROR: "Plans could not be loaded. Try again shortly.",
  BILLING_OVERVIEW: "Billing overview",
  BILLING_OVERVIEW_SUBTITLE: "Current quota, subscriptions and available plans.",
  STUDENT_LIMIT: "Student limit",
  CURRENT_ROSTER_USAGE_LABEL: "Current roster usage",
  ACTIVE_SUBSCRIPTIONS: "Active subscriptions",
  LOADED_FROM_API: "Loaded from API",
  AVAILABLE_PLANS: "Available plans",
  ACTIVE_CATALOG_ENTRIES: "Active catalog entries",
  EXAM_PACKAGES: "Exam packages",
  EXAM_PACKAGES_SUBTITLE: "Time-limited access with a student cap per exam.",
  LOADING_PLANS: "Loading plans...",
  STUDENT_CAPACITY: "Student capacity",
  STUDENT_CAPACITY_SUBTITLE: "Permanent quota add-ons, separate from exam packages.",
  VIEW_ORDER_HISTORY: "View order history",
  REDEEM_LICENSE: "Redeem a license code",
  PLAN_DURATION: (days: number) => `${days} days`,
  PERMANENT: "Permanent",
  NO_DESCRIPTION: "No description provided.",
  BUY_NOW: "Buy now",
} as const;

export const PAYMENT_STATE_MESSAGES: Record<string, string> = {
  PENDING: "We are waiting for PayOS confirmation.",
  PAID: "Your plan is active and ready to use.",
  CANCELLED: "This order was cancelled.",
  EXPIRED: "This payment link has expired. Start a new order.",
};
