export const PUBLIC_TEXT = {
  BRAND: "PTE Prep",
  HOME_ARIA_LABEL: "PTE Prep home",
  LOGO_ALT: "PTE Prep logo",
  FOCUS_DESCRIPTION: "Focused exam operations for modern organizations.",
  PRODUCT: "Product",
  EXAM_PACKAGES: "Exam packages",
  STUDENT_CAPACITY: "Student capacity",
  ACCOUNT: "Account",
  SIGN_IN: "Sign in",
  REGISTER_ORGANIZATION: "Register organization",
  ACCESS: "Access",
  ACCESS_DESCRIPTION: "Apply, get approved, then choose a plan.",
  COPYRIGHT: "© 2026 PTE Prep",
  MAIN_NAVIGATION: "Main navigation",
  PLANS: "Plans",
  DASHBOARD: "Dashboard",
  PERMANENT_ADD_ON: "Permanent add-on",
  PLAN_DURATION: (days: number) => `${days} days`,
  EMPTY_VALUE: "—",
  UP_TO_STUDENTS: (count: number | string) => `Up to ${count} students / exam`,
  EXTRA_STUDENTS: (count: number | string) => `+${count} students`,
  NO_DESCRIPTION: "No description provided.",
  BUY_NOW: "Buy now",
  ARROW: "→",
  LOADING_PLANS: "Loading available plans...",
  PLANS_LOAD_ERROR: "Plans could not be loaded. Try again shortly.",
  NO_PLANS: "No plans are currently available.",
  STUDENT_CAPACITY_ADD_ONS: "Student capacity add-ons",
} as const;
