import type { StudentAttemptStatus } from "@pte/api-client";

export type StudentDetailTab = "account" | "overview" | "history";

export const STUDENT_DETAIL_TEXT = {
  backToStudents: "← Students",
  profileLoadFailed: "Unable to load student details.",
  genericError: "We couldn't complete this request. Please try again.",
  emptyValue: "—",
  studentCodeMissing: "No student code",
  status: {
    active: "Active",
    suspended: "Suspended",
  },
  tabs: {
    account: "Account information",
    overview: "Overview",
    history: "Exam history",
    ariaLabel: "Student information sections",
  },
  actions: {
    menuLabel: "Student actions",
    generatePassword: "Generate temporary password",
    reactivate: "Reactivate account",
    suspend: "Suspend account",
  },
  suspendDialog: {
    title: "Suspend student account",
    description: (name: string): string =>
      `Suspend ${name}'s account? They will not be able to sign in until reactivated.`,
    confirm: "Suspend account",
    cancel: "Cancel",
  },
  account: {
    title: "Account information",
    subtitle: "Student identity and contact information.",
    edit: "Edit",
    save: "Save information",
    saved: "Student information updated.",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    dateOfBirth: "Date of birth",
    username: "Username",
    studentCode: "Student code",
    roles: "Roles",
    status: "Status",
    className: "Current class",
    programName: "Current program",
    passwordChange: "First-login password change",
    required: "Required",
    notRequired: "Not required",
    noClass: "Not assigned to a class",
    noProgram: "No program",
  },
  overview: {
    attemptCount: "Exam attempts",
    averageOverall: "Overall average",
    averageFromPublished: "Based on published reports",
    averageInsufficient: "Not enough official data",
    latestAttempt: "Latest attempt",
    skillTitle: "Scores by skill",
    skillDescription: "Only published reports with an immutable snapshot are included.",
    insufficientData: "Not enough data",
    noScoredAttempt: "No attempt has enough scored data yet.",
    progressLabel: (skill: string): string => `${skill} score`,
    reportCount: (count: number): string => `${count} valid report(s)`,
  },
  history: {
    from: "From date",
    to: "To date",
    status: "Status",
    allStatuses: "All statuses",
    created: "Not started",
    inProgress: "In progress",
    submitted: "Submitted",
    session: "Exam",
    attempt: "Attempt",
    report: "Report",
    time: "Time",
    published: "Published",
    unpublished: "Processing",
    legacy: "Legacy report",
    unavailable: "No report",
    overallScore: (score: number): string => `Overall: ${score}`,
    emptyTitle: "No exam history",
    emptyDescription: "No attempts match the current filters.",
  },
  skills: {
    LISTENING: "Listening",
    READING: "Reading",
    SPEAKING: "Speaking",
    WRITING: "Writing",
  },
} as const;

export const STUDENT_HISTORY_STATUS_VALUES: readonly (StudentAttemptStatus | "ALL")[] = [
  "ALL",
  "SUBMITTED",
  "IN_PROGRESS",
  "CREATED",
];
