import type { ApiClient } from "../../client/client";
import type {
  AdminLoginRequest,
  AuthResponse,
  ChangePasswordRequest,
  HostLoginRequest,
  LoginRequest,
  LogoutRequest,
  RefreshTokenRequest,
  StudentLoginRequest,
} from "../../types/auth";

export const AUTH_ENDPOINTS = {
  login: "/api/auth/login",
  refresh: "/api/auth/refresh",
  logout: "/api/auth/logout",
  /**
   * No backend controller anywhere in `pte-api` exposes this — identity's
   * `AuthController` only has `/login`, `/refresh`, `/logout` (verified via
   * repo-wide grep for `change-password`/`ChangePassword`). Deliberately
   * left as a plausible-but-fictitious path rather than removed, matching
   * `types/account/index.ts`'s `CurrentUser` treatment — unused anywhere
   * in these apps today (confirmed via grep), not wired to anything real.
   *
   * <p>Phase 8 of the commercialization work added `mustChangePassword` to
   * the login response, so a real first-login password-change endpoint is
   * now genuinely needed — but it does not exist yet on the backend.
   */
  changePassword: "/api/auth/change-password",
} as const;

export function login(client: ApiClient, payload: LoginRequest): Promise<AuthResponse> {
  return client.request<AuthResponse>(AUTH_ENDPOINTS.login, {
    method: "POST",
    body: payload,
  });
}

export function loginAdmin(client: ApiClient, payload: AdminLoginRequest): Promise<AuthResponse> {
  return login(client, {
    username: payload.username,
    password: payload.password,
  });
}

export function loginHost(client: ApiClient, payload: HostLoginRequest): Promise<AuthResponse> {
  return login(client, {
    username: payload.username,
    password: payload.password,
  });
}

/**
 * A STUDENT's username is `{tenant.code}.{random}` (generated by roster
 * import), not an email address — so this is a straight pass-through now.
 * Before the login key moved from email to username it had to map
 * `username` onto an `email` field, which was never a verified contract.
 */
export function loginStudent(
  client: ApiClient,
  payload: StudentLoginRequest,
): Promise<AuthResponse> {
  return login(client, {
    username: payload.username,
    password: payload.password,
  });
}

export function refreshAuth(
  client: ApiClient,
  payload: RefreshTokenRequest,
): Promise<AuthResponse> {
  return client.request<AuthResponse>(AUTH_ENDPOINTS.refresh, {
    method: "POST",
    body: payload,
  });
}

export function logout(client: ApiClient, payload: LogoutRequest): Promise<void> {
  return client.request<void>(AUTH_ENDPOINTS.logout, {
    method: "POST",
    body: payload,
  });
}

export function changePassword(client: ApiClient, payload: ChangePasswordRequest): Promise<void> {
  return client.request<void>(AUTH_ENDPOINTS.changePassword, {
    method: "POST",
    body: payload,
  });
}
