export const PLATFORM_USER_TEXT = {
  TITLE: "Platform users",
  SUBTITLE: "Manage platform managers and academic staff accounts.",
  CREATE: "Create platform user",
  CREATE_TITLE: "Create platform user",
  EDIT_TITLE: "Update platform roles",
  EMAIL: "Email",
  FULL_NAME: "Full name",
  PASSWORD: "Temporary password",
  SEARCH_PLACEHOLDER: "Search by name or email",
  ROLE: "Role",
  STATUS: "Status",
  FILTER_ROLE: "Filter by role",
  FILTER_STATUS: "Filter by status",
  ALL_ROLES: "All roles",
  ALL_STATUSES: "All statuses",
  ACTIONS: "Actions",
  CREATED: "Platform user created.",
  UPDATED: "Platform roles updated.",
  SUSPENDED: "Platform user suspended.",
  REACTIVATED: "Platform user reactivated.",
  SAVE: "Save changes",
  CANCEL: "Cancel",
  LOADING: "Loading platform users...",
  EMPTY: "No platform users found.",
  ERROR: "Unable to load platform users.",
  RETRY: "Retry",
  FORM_ERROR: "Please complete all required fields.",
  PASSWORD_HELP: "Use at least 8 characters. The password is shown only during creation.",
  SUSPEND: "Suspend",
  REACTIVATE: "Reactivate",
  EDIT_ROLES: "Update roles",
  SUSPEND_CONFIRM: "Suspend this platform user? They will no longer be able to sign in.",
} as const;

export const PLATFORM_ASSIGNABLE_ROLE_OPTIONS = [
  { value: "PLATFORM_MANAGER", label: "Platform manager" },
  { value: "ACADEMIC_MANAGER", label: "Academic manager" },
  { value: "ACADEMIC_STAFF", label: "Academic staff" },
] as const;
